export const THIRDWEB_CLIENT_ID = process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID;
export const ORIGIN_CLIENT_ID = process.env.NEXT_PUBLIC_ORIGIN_API;
export const THIRDWEB_SECRET_ID = process.env.NEXT_PUBLIC_THIRDWEB_SECRET_ID;
export const WALLETCONNECT_PROJECT_ID = process.env.WALLETCONNECT_PROJECT_ID;
export const GRAPHQL_ENDPOINT = process.env.GRAPHQL_ENDPOINT;
export const NEXT_PUBLIC_PINATA_JWT = process.env.NEXT_PUBLIC_PINATA_JWT;
export const NEXT_PUBLIC_PINATA_GATEWAY = process.env.NEXT_PUBLIC_PINATA_GATEWAY;
